name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:

   job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run:  npm install   

    - name: Install Angular CLI
      run:  npm install -g @angular/cli

    - name: Run tests
      run:  ng test --watch=false --browsers=ChromeHeadless
    
    - name: Deploy to GitHub Pages
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /LB322/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/lb322

