name: Lint

on:
  push:
    branches-ignore:    
      - 'main'
      - 'master'
      - 'gh-pages'

env: 
  NODE_VERSION: 16

jobs: 
  linting:
    name: Linting 
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Code Linting
        run: npm run lint
        
      - name: Code Linting Fix
        run: ng lint --fix=true
